# Generated by Django 4.2.10 on 2024-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_author_born_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
